### ISSUE TITLE
Scraper should persist scraped courses

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/UofT-Bird-Courses#1]
As the scraper scrapes through UofT Course Evals, it could write the evaluation data to a csv or json file for the frontend to display.

**Comment by lunaroyster** [comment]
Scrape's is available on the Teams group, in files.

The script could be faster (Scraping every row makes a call through Selenium, and we can probably batch that). But it's infrequent, so that's okay.

**Comment by ArsalaBangash** [comment]
Well done!
